### PR TITLE
Systemdfix

### LINKED ISSUE #1: The systemd service doesn't work due to issues in autoanswer.py
Systemd starts autoanswer.py using the following command:

`/usr/bin/python /opt/autoanswer.py < /dev/null`

This causes the python script to run and exit with `(code=exited, status=0/SUCCESS)` when the python script should stay alive and wait for inbound calls.

### PR DESCRIPTION
**Pull request by runvnc**
Fixes #1 . You may want to double-check that it is actually answering still - I assume it is but its late and I am just starting to get familiar with this.  

I checked with htop and the 200ms loop doesn't seem to do anything noticeable to CPU usage.

### CODE REVIEW

**Comment by danry25** [comment]
Hmm, on a fresh Debian 8 install I get the following error when starting the paging service with `sudo service paging start`:

```
user@debian:~/PagingServer$ sudo service paging status
● paging.service - SIP client that autoanswers, perfect for a Paging system
   Loaded: loaded (/etc/systemd/system/paging.service; enabled)
   Active: deactivating (stop) (Result: exit-code) since Tue 2015-08-04 03:26:54 PDT; 1s ago
  Process: 16144 ExecStart=/usr/bin/python /opt/autoanswer.py start (code=exited, status=1/FAILURE)
 Main PID: 16144 (code=exited, status=1/FAILURE);         : 16148 (python)
   CGroup: /system.slice/paging.service
           └─control
             └─16148 /usr/bin/python /opt/autoanswer.py stop

Aug 04 03:26:53 debian python[16144]: daemon_runner = runner.DaemonRunner(app)
Aug 04 03:26:53 debian python[16144]: File "/usr/local/lib/python2.7/dist-packages/daemon/runner.py", line 111, in __init__
Aug 04 03:26:53 debian python[16144]: self.daemon_context.stdout = open(app.stdout_path, 'w+t')
Aug 04 03:26:53 debian python[16144]: IOError: [Errno 6] No such device or address: '/dev/tty'
Aug 04 03:26:54 debian python[16144]: Sentry responded with an API error: APIError(Invalid api key)
Aug 04 03:26:54 debian python[16144]: [u"IOError: [Errno 6] No such device or address: '/dev/tty'", u'  File "/opt/autoanswer.py", line 134, in <m..._init__']
Aug 04 03:26:54 debian python[16144]: Sentry is attempting to send 1 pending error messages
Aug 04 03:26:54 debian python[16144]: Waiting up to 10 seconds
Aug 04 03:26:54 debian python[16144]: Press Ctrl-C to quit
Aug 04 03:26:54 debian systemd[1]: paging.service: main process exited, code=exited, status=1/FAILURE
Aug 04 03:26:55 debian python[16148]: Traceback (most recent call last):
Aug 04 03:26:55 debian python[16148]: File "/opt/autoanswer.py", line 134, in <module>
Aug 04 03:26:55 debian python[16148]: daemon_runner = runner.DaemonRunner(app)
Aug 04 03:26:55 debian python[16148]: File "/usr/local/lib/python2.7/dist-packages/daemon/runner.py", line 111, in __init__
Aug 04 03:26:55 debian python[16148]: self.daemon_context.stdout = open(app.stdout_path, 'w+t')
Aug 04 03:26:55 debian python[16148]: IOError: [Errno 6] No such device or address: '/dev/tty'
Hint: Some lines were ellipsized, use -l to show in full.
```

Changing `self.stdout_path =` and `self.stderr_path =` to  /dev/null from /dev/tty in autoanswer.py seems to worsen the issue, not sure what the best way to fix this issue is.

Additionally, this process should not be run as root, should I create a (low privilege) user and have the systemd unit file use that?

Note: The script still answers inbound calls, need to throw a few thousand calls at it to test stability though.

**Comment by runvnc** [comment]
I used root because I did not have a 'dan' on my system, it was late, and its usually easier to get things working with root because it had permission.

I did not get any errors on my own fresh debian install.  Please try with root so we can help diagnos the issue.  If it works with root on your system then maybe dan needs more privileges.

One thing though I was testing with systemctl start paging.service since that's what you had in the readme.

I am well aware of the deep hatred for the root user and wasn't trying to make you use it.  It was just late and I didn't want to set up 'dan' at that time.

**Comment by runvnc** [comment]
Also another thing I thought of, according to the mailing list pjsip may need a terminal.  Rather than trying to patch pjsip I would just give it a fake terminal: http://stackoverflow.com/questions/1401002/trick-an-application-into-thinking-its-stdin-is-interactive-not-a-pipe (search page for `function faketty { script -qfc "$(printf "%q " "$@")"; }`)

See http://lists.pjsip.org/pipermail/pjsip_lists.pjsip.org/2007-September/000082.html

```
> I know it expects stdin and stdout, but I have 
> run numerous processes in the background before that expect stdin and 
> stdout without any problems.

That's because of stdin reading by pjsua. Have a look at 
pjsua_app.c, and disable the call to console_app_main() (replace it 
with "while (1) sleep(1000);" or something like that).
```

That's going to be toug to maintain so I would try the faketty.  May be able to work on this more later but with the $12/hr rate it might have to be a slightly lower priority.  Although I do appreciate your helping me out, every bit helps in my situation.

**Comment by mk-fg** [comment]
Thanks for your work.

I just merged #9 - a different implementation of a "daemon mode", with just two options:
- Run in the foreground - default mode, useful for running it thing from terminal, e.g. in --debug mode, or with any daemon-baby-sitter like start-stop-daemon (debian's old sysvinit crutch), daemontools, upstart, runit, or what have you.
  
  I don't think pulling in another dep just to add "forking" mode, as done here, is worth it, because forking mode itself is pointless on modern systems, or even 5-year-old debians, where you always have much-much better options for daemonization (listed above).
- Run with --systemd flag, for dedicated systemd integration. Most stuff happening here I've described in https://github.com/AccelerateNetworks/PagingServer/issues/1#issuecomment-127662605
  
  As systemd has now made its way even into the most thick-skinned and enterprise distros like RHEL, Debian, Ubuntu, SUSE, CoreOS, Arch, etc - I expect this mode should be pretty much the default for any non-debug runs.

Doesn't require any extra deps (obviously systemd in the second case, but only if one uses that flag) and should work better with expected-default mode - systemd, described more in-depth on why in #1, I think.

Approach taken in this PR I think goes for the wrong thing (trying to do daemonization stuff that systemd already does for free), and has quite a few issues, which mostly pop out of doing all this redundant weirdness, not needed in the first place.

---

Wrt stdout/stderr btw, it shouldn't be a concern under systemd, in fact it's actually useful for daemons to log their stuff there instead of some special-case and obscure files, which they manage haphazardly god-knows-where on the fs.
With standard streams and default service settings under systemd, you get output of such apps in `systemctl status paging` and `journalctl -u paging`.

Error above seem to be due to the fact that python "daemon" module, as a part of a "proper" daemonization sequence, closes fd's like 0 and 1, then switches uid, while pjsua then tries to later re-open them, while no longer being able to after uid switch.

Shouldn't be a concern at all with now-current implementation, as there's no need to close random fd's under systemd, it does that for every service before starting it (and pid-1 doesn't have "random fds" as e.g. bash script might, to begin with).

---

Apologies if it's a bit thick on systemd and unix stuff, and maybe unnecessary details, but didn't want to just close PR without proper rationale.

**Comment by runvnc** [comment]
Ok, just to be clear, as far as I can tell, what I had set up and the fake
tty would work perfectly fine without having to maintain a fork of pjsua.
You just think you have a better way.  I think what should have been done
was exactly what I suggested.  That was the simplest way to meet the
requirements.

There is nothing wrong with pulling in a dependency.  What you have done is
added quite a lot of complexity to the task without achieving anything of
real value.  They could have simply started it as a daemon for the normal
course.

**Comment by mk-fg** [comment]
> as far as I can tell, what I had set up and the fake tty would work perfectly fine without having to maintain a fork of pjsua.

There's no need to maintain a fork of pjsua with either approach, I think you misunderstand what I meant by "forking", hence the "maintain a fork of pjsua" misconception.

What I mean by "forking" is described here, for example: https://en.wikipedia.org/wiki/Fork_%28system_call%29

It's the most basic thing on any unix system, where after kernel boots, only single "process" (pid) is started, pid-1 or "init", and then every single other process gets created by either "fork()" (usually followed by "exec*()") or "clone()" syscalls.

And with unix daemons on starting on OS boot, "forking" has even more complicated meaning than just a syscall, referring to part of a "daemon app lifecycle" (see http://www.freedesktop.org/software/systemd/man/daemon.html for good description of the "daemonization" process I was referring to above).

The latter is the "forking" I was referring to.

---

Approach you proposed implements old SysV-style forking daemon, assuming that the thing will be started from unclean and unpredictable environment, like some init shell script or an interactive shell, which is not the case with pretty much any modern system (my comment above sums it up too, I think).

To make the thing start from systemd, as I've mentioned as the first mode in the comment above, you don't need that "daemon" wrapping in python at all, e.g. service file like this:

```
[Service]
User=myuser
ExecStart=/path/to/my/script.py
```

Will work perfectly fine, and won't have issues with stdout/stderr.

I.e. that whole daemon wrapper you've added is completely unnecessary in this case.

Not only that, but complicates stuff like logging, does unnecessary stuff on start, requires more complicated pid-tracking, etc.

What I did in #9 is not making script do same unnecessary stuff (which any modern init system does for you already), but rather the stuff I've mentioned in https://github.com/AccelerateNetworks/PagingServer/issues/1#issuecomment-127662605.

**Comment by mk-fg** [comment]
> That was the simplest way to meet the requirements.

I disagree, as noted above - it was unnecessary, only thing that was needed there is for script not to exit immediately, e.g. by running pjsua in the main thread (as 010621b does, among other things), `while True: sleep()` is another option to do the same thing, which was mentioned. That was it.

> There is nothing wrong with pulling in a dependency.

Yeah, it's not a problem in general, and not a problem with this particular PR either.
It's adding the dep to make stuff more complicated and broken for no gain that seems wrong to me.

**Pull request closed without merging**
